# Generated by Django 2.1.7 on 2020-11-12 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=11)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=10)),
                ('group', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZendeskUserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied_licenses', models.CharField(blank=True, max_length=2, null=True)),
                ('current_admins', models.CharField(blank=True, max_length=2, null=True)),
                ('current_agents', models.CharField(blank=True, max_length=2, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('excec_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='zendeskuser',
            name='hist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='zendesk.ZendeskUserHistory'),
        ),
    ]
