# Generated by Django 2.1.7 on 2020-11-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0003_auto_20201112_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zendeskuserhistory',
            old_name='occupied_licenses',
            new_name='total_occupied_licenses',
        ),
    ]
