# Generated by Django 2.1.7 on 2020-11-13 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0005_auto_20201112_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zendeskuser',
            options={'permissions': (('view_active_zendesk_user_list', 'View active Zendesk userlist'), ('get_active_zendesk_user_list', 'Get active Zendesk userlist'), ('export_active_zendesk_user_list', 'Export Zendesk userlist')), 'verbose_name': 'Zendesk User'},
        ),
        migrations.AlterModelOptions(
            name='zendeskuserhistory',
            options={'permissions': (('view_zendesk_active_user_hist', 'View Zendesk active User History'),), 'verbose_name': 'Request History', 'verbose_name_plural': 'User Request Histories'},
        ),
    ]
