# Generated by Django 2.1.7 on 2020-11-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0006_auto_20201112_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zendeskuserhistory',
            old_name='excec_user',
            new_name='exec_user',
        ),
    ]
