# Generated by Django 2.1.7 on 2020-11-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0011_auto_20201123_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskuser',
            name='hist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zendesk.ZendeskUserHistory'),
        ),
    ]
