# Generated by Django 2.1.7 on 2020-12-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0015_auto_20201202_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskuserhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
