# Generated by Django 2.1.7 on 2020-12-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0016_auto_20201202_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskuserhistory',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
