# Generated by Django 2.1.7 on 2020-12-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0017_auto_20201202_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskuserhistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
