# Generated by Django 2.1.7 on 2020-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0018_auto_20201202_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskuserhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
