# Generated by Django 2.1.7 on 2021-03-08 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zendesk', '0020_auto_20201202_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskuserhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 19, 57, 54, 973314, tzinfo=utc)),
        ),
    ]
