# Generated by Django 2.1.7 on 2019-09-05 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ambassador', models.CharField(max_length=20, null=True)),
                ('no_ambassador', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('second_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('id_puesto', models.CharField(max_length=4, null=True)),
                ('id_area_chief', models.CharField(max_length=4, null=True)),
                ('id_area_dir', models.CharField(max_length=4, null=True)),
                ('id_area_ger', models.CharField(max_length=4, null=True)),
                ('id_area_jef', models.CharField(max_length=4, null=True)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('no_ambassador_boss', models.CharField(max_length=20, null=True)),
                ('id_ambassador_status', models.CharField(max_length=2, null=True)),
                ('id_station', models.CharField(max_length=4, null=True)),
                ('genere', models.CharField(max_length=20, null=True)),
                ('id_cc_nomina', models.CharField(max_length=4, null=True)),
                ('id_cc_pases', models.CharField(max_length=4, null=True)),
                ('id_cc_cobus', models.CharField(max_length=4, null=True)),
                ('ingress_date', models.CharField(max_length=20, null=True)),
                ('birth_date', models.CharField(max_length=20, null=True)),
                ('rfc', models.CharField(max_length=25, null=True)),
                ('curp', models.CharField(max_length=25, null=True)),
                ('plaza', models.CharField(max_length=20, null=True)),
                ('process', models.CharField(max_length=2, null=True)),
                ('id_enterprise', models.CharField(max_length=4, null=True)),
                ('registry_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_applicant_list', 'Can visualize applicant list'), ('create_applicant', 'Can create applicant'), ('can_disable_applicant', 'Can disable Applicant')),
            },
        ),
    ]
