# Generated by Django 2.1.7 on 2019-05-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'permissions': (('can_disable_applicant', 'Can disable Applicant'),)},
        ),
    ]
