# Generated by Django 2.1.7 on 2019-05-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20190501_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'permissions': (('view_applicant_list', 'Can visualize applicant list'), ('create_applicant', 'Can create applicant'), ('can_disable_applicant', 'Can disable Applicant'))},
        ),
    ]
