# Generated by Django 2.1.7 on 2020-03-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20191205_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='genere',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_ambassador_status',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_area_chief',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_area_dir',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_area_ger',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_area_jef',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_puesto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
