# Generated by Django 2.1.7 on 2019-07-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20190505_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='last_name',
            new_name='frst_lastname',
        ),
        migrations.AddField(
            model_name='applicant',
            name='birth_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='curp',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='genere',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_ambassador',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_ambassador_status',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_area_chief',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_area_dir',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_area_ger',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_area_jef',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_cc_cobus',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_cc_nomina',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_cc_pases',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_enterprise',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_puesto',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_station',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ingress_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='no_ambassador',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='no_ambassador_boss',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='plaza',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='process',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rfc',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='scnd_lastname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
