# Generated by Django 2.1.7 on 2019-07-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20190725_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id_area_chief',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_area_dir',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_area_ger',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_area_jef',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_enterprise',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_puesto',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
