# Generated by Django 2.1.7 on 2020-03-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20200311_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='registry_date',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_reg_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
