# Generated by Django 2.1.7 on 2020-03-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_auto_20200311_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant_reg_date',
            new_name='registry_date',
        ),
    ]
