
#Type
REGISTRY = 'Registry'
UNSUBSCRIBE = 'Unsubscribe'
UPDATE = 'Update'
IMPLEMENTATION = 'Implementation'
TRAINING = 'Training'
GUIDE = 'Guide'

TYPE = (
    (REGISTRY, 'registry'),
    (UNSUBSCRIBE, 'unsubscribe'),
    (UPDATE, 'update'),
)

#Inc source
PAPERLESS = 'Paperless'
BAJAS_TALENTO = 'Bajas Talento'
OTHER = 'Other'

INC_SOURCE = (
    (PAPERLESS, 'paperless'),
    (BAJAS_TALENTO, 'bajas talento'),
    (OTHER, 'other'),
)

#Ambassador TYPE
AEROPUERTOS = 'Aeropuertos'
SOBRECARGOS = 'Sobrecargos'
CALL_CENTER = 'Call Center'

AMBASSADOR_TYPE = (
    ('AEROPUERTOS', AEROPUERTOS),
    ('SOBRECARGOS', SOBRECARGOS),
    ('CALL_CENTER', CALL_CENTER),
)

INTERNAL = 'Internal'
EXTERNAL = 'External'

AMBASSADOR_TYPE = (
    ('INTERNAL', INTERNAL),
    ('EXTERNAL', EXTERNAL),
)

#Nettracer Stations
"""
CLAIMS = 'Claims'
STATIONS = (

)
"""

#SmartKargo Roles
GSA = 'GSA (Operations)'
GHA = 'GHA'

SK_ROLES = (
    (GSA,'GSA'),
    (GHA, 'GHA'),
)

#Zendesk Groups
#Rol
USUARIO_FINAL = 'Usuario Final'
ADMINISTRADOR = 'Administrador'
AC_AGENTE_CC = 'AC_AGENTE_CC'
AC_AALISTA_HQ = 'AC_Analista HQ'
AC_ANALISTA_HQ_CR = 'AC_Analista HQ CR'
AC_Embajador_HQ = 'AC_Embajador HQ'
AC_ESPECIALISTA_HQ = 'AC_Especialista HQ'
AC_JEFE_AEROPUERTO = 'AC_Jefe Aeropuerto'
AC_SUPERVISOR_CC = 'AC_Supervisor CC'
AC_SUPERVISOR_HQ = 'AC_Supervisor HQ'
AUDITORIA = 'Auditoria'
INTEGRADOR = 'Integrador'
OPTIMIZADOR = 'Optimizador'
ROl_ANALISTA_IINSIGHTS = 'Rol-Analista Insights'
YV_AGENTE_YA_VAS = 'YV_Agente Ya Vas'
AGENTE_EXCLUSIVO_PARA_CHAT = 'Agente exclusivo para chat'

#Grupos
AC_AEROPUERTOS = 'AC_Aeropuertos'
AC_AGENTE_CC_ASG = 'AC_Agente CC ASG'
AC_AGENTE_CC_ATE_BO1 = 'AC_Agente CC ATE BO1'
AC_AGENTE_CC_BO2 = 'AC_Agente CC BO2'
AC_AGENTE_ATE_REDES = 'AC_Agente ATE Redes'
AC_AGENTE_CC_ATE_SKILL = 'AC_Agente CC ATE Skill'
AC_AGENTE_CC_CRC = 'AC_Agente CC CRC'
AC_AGENTE_CC_PROTEX = 'AC_Agente CC Protex'
AC_AGENTE_CC_TXP_E = 'AC_Agente CC TXP'
AC_AGENTE_CC_TXP_1 = 'AC_Agente CC TXP 1'
AC_AGENTE_CC_XQ = 'AC_Agente Cc XQ'
AC_AGENTE_CC_XQ_BO1 = 'AC_Agente CC XQ BO1'
AC_ANALISTA_HQ_ASG = 'AC_Analista HQ ASG'
"""
AC_ANALISTA_HQ_CSA
AC_ANALISTA_HQ_CXC
AC_ANALISTA_HQ_CXP
AC_ANALISTA_HQ_ITINERARIOS
AC_ANALISTA_HQ_TES
AC_ANALISTA_HQ_XQ
AC_BOR_VOLANTIO
AC_COORDINADOR_CC
AC_CUSTOMER_RESOLUTION
AC_ESPECIALISTA_HQ_CR
AC_FACTURACION
AC_GERENTE_CC
AC_GERENTE_DE_PROTECCIONES_Y4
AC_JEFE_HQ_CR
AC_JEFE_HQ_CXC
AC_JEFE_HQ_XQ_ATO
AC_JEFE_ATO_ACA
AC_JEFE_ATO_AGU
AC_JEFE_ATO_AUS
AC_JEFE_ATO_BJX
AC_JEFE_ATO_CBX
AC_JEFE_ATO_CEN
AC_JEFE_ATO_CJS
AC_JEFE_ATO_CLQ
AC_JEFE_ATO_CTM
AC_JEFE_ATO_CUL
AC_JEFE_ATO_CUN
AC_JEFE_ATO_CUU
AC_JEFE_ATO_CZM
AC_JEFE_ATO_DEN
AC_JEFE_ATO_DFW
AC_JEFE_ATO_DGO
AC_JEFE_ATO_FAT
AC_JEFE_ATO_GDL
AC_JEFE_ATO_GUA
AC_JEFE_ATO_HMO
AC_JEFE_ATO_HUX
AC_JEFE_ATO_IAH
AC_JEFE_ATO_JFK
AC_JEFE_ATO_LAP
AC_JEFE_ATO_LAS
AC_JEFE_ATO_LAX
AC_JEFE_ATO_LMM
AC_JEFE_ATO_MCO
AC_JEFE_ATO_MDW
AC_JEFE_ATO_MEX
AC_JEFE_ATO_MGA
AC_JEFE_ATO_MIA
AC_JEFE_ATO_MID
AC_JEFE_ATO_MKE
AC_JEFE_ATO_MKM
AC_JEFE_ATO_MTY
AC_JEFE_ATO_MXL
AC_JEFE_ATO_MZT
AC_JEFE_ATO_OAK
AC_JEFE_ATO_OAX
AC_JEFE_ATO_ONT
AC_JEFE_ATO_ORD
AC_JEFE_ATO_PBC
AC_JEFE_ATO_PDX
AC_JEFE_ATO_PHX
AC_JEFE_ATO_PVR
AC_JEFE_ATO_QRO
AC_JEFE_ATO_REX
AC_JEFE_ATO_RNO
AC_JEFE_ATO_SAL
AC_JEFE_ATO_SAT
AC_JEFE_ATO_SEA
AC_JEFE_ATO_SJC
AC_JEFE_ATO_SLP
AC_JEFE_ATO_SMF
AC_JEFE_ATO_TAP
AC_JEFE_ATO_TGZ
AC_JEFE_ATO_TIJ
AC_JEFE_ATO_TPQ
AC_JEFE_ATO_TRC
AC_JEFE_ATO_UPN
AC_JEFE_ATO_VER
AC_JEFE_ATO_VSA
AC_JEFE_ATO_ZCL
AC_JEFE_ATO_ZIH
AC_JEFE_ATO_CXC
AC_PROTECCIONES
AC_REDES_CONVERSIONAL
AC_SATRISFACCION
AC_SMARTCHART
AC_SUPERVISOR_ASG
AC_SUPERVISOR_CC_ATE
AC_SUPERVISOR_CC_XQ
ADMIN_IT
CONSULTA
TICKETS_ONLINE_REFOUND_ABIERTOS
VOI_OBSERVACIONES
YV_BACKOFFICE_YAVAS
"""


AC_AGENTE_CC_XQ = 'AC_AGENTE_CC_XQ'

"""
AGENT_GROUP = (

)
"""
