# Generated by Django 2.1.7 on 2019-03-07 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0004_auto_20190301_1246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOXRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(blank=True, max_length=15, null=True)),
                ('request_type', models.CharField(choices=[('registration', 'Registration'), ('unsubscribe', 'Unsubscribe')], default='registration', max_length=5)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('current_user', models.CharField(blank=True, max_length=200)),
                ('mail', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('first_source', models.CharField(choices=[('baja talento', 'Baja de Talento'), ('sharepoint', 'Sharepoint'), ('service now', 'Service Now')], default='sharepoint', max_length=50)),
                ('from_source_date', models.CharField(blank=True, max_length=25)),
                ('registry_date', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('folio_number', models.CharField(default='', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='low', max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in progress', 'In Progress'), ('assigned', 'Assigned'), ('approval proccess provider', 'Approval Proccess Provider')], default='open', max_length=15)),
                ('registry_date', models.DateField(auto_now_add=True)),
                ('request_type', models.CharField(choices=[('registration', 'Registration'), ('unsubscribe', 'Unsubscribe')], default='registration', max_length=5)),
                ('beneficiary_name', models.CharField(blank=True, max_length=50)),
                ('beneficiary_last_name', models.CharField(blank=True, max_length=50)),
                ('approval_owner', models.CharField(blank=True, max_length=15)),
                ('approval_executor', models.CharField(blank=True, max_length=50)),
                ('approve', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('item_type', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=150)),
                ('solution_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('close_comment', models.TextField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.Applicant')),
                ('application', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='application.Application')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=450)),
                ('registry_date', models.DateTimeField(auto_now=True)),
                ('change_type', models.BooleanField(default=True)),
                ('not_finished_type', models.BooleanField(default=False)),
                ('sox', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.SOXRegistry')),
                ('ticket', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Ticket')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
