# Generated by Django 2.1.7 on 2019-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='folio_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
