# Generated by Django 2.1.7 on 2019-03-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190307_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approval_executor',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='approval_owner',
            field=models.CharField(choices=[('approval', 'Approval')], default='approval', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item_type',
            field=models.CharField(choices=[('item', 'Item')], default='item', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('unsubscribe', 'Unsubscribe')], default='registration', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in progress', 'In Progress'), ('assigned', 'Assigned'), ('approval proccess provider', 'Provider Approval Proccess')], default='open', max_length=15),
        ),
    ]
