# Generated by Django 2.1.7 on 2019-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190307_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='registry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
