# Generated by Django 2.1.7 on 2019-03-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_tickethistory_sox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in progress', 'In Progress'), ('assigned', 'Assigned'), ('approval proccess provider', 'Provider Approval Proccess')], default='open', max_length=50),
        ),
    ]
