# Generated by Django 2.1.7 on 2019-03-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20190313_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickethistory',
            old_name='change_type',
            new_name='update',
        ),
    ]
