# Generated by Django 2.1.7 on 2019-03-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20190313_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soxregistry',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='soxregistry',
            name='user',
        ),
        migrations.DeleteModel(
            name='SOXRegistry',
        ),
    ]
