# Generated by Django 2.1.7 on 2019-05-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20190314_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('can_disable_ticket', 'Puede inhabilitar un ticket'),)},
        ),
    ]
