# Generated by Django 2.1.7 on 2019-05-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20190501_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('can_disable_ticket', 'Can disable ticket'),)},
        ),
    ]
