# Generated by Django 2.1.7 on 2019-05-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20190501_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('can_close_ticket', 'Can close current ticket'), ('can_view_ticket_detail', 'Can visualize current ticket detail'), ('can_disable_ticket', 'Can disable ticket'))},
        ),
    ]
