# Generated by Django 2.1.7 on 2019-05-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20190501_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('view_ticket_list', 'Can view the tickets list'), ('close_ticket', 'Can close current ticket'), ('view_ticket_detail', 'Can visualize current ticket detail'), ('disable_ticket', 'Can disable ticket'))},
        ),
    ]
