# Generated by Django 2.1.7 on 2019-05-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20190505_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('view_ticket_list', 'Can view the tickets list'), ('create_ticket', 'Can create new ticket'), ('close_ticket', 'Can close current ticket'), ('view_ticket_detail', 'Can visualize current ticket detail'), ('disable_ticket', 'Can disable ticket'))},
        ),
    ]
