# Generated by Django 2.1.7 on 2019-05-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20190505_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickethistory',
            old_name='not_finished_type',
            new_name='finished',
        ),
    ]
