# Generated by Django 2.1.7 on 2019-03-14 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0004_auto_20190301_1246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOXRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(blank=True, max_length=15, null=True)),
                ('request_type', models.CharField(choices=[('registration', 'Registration'), ('unsubscribe', 'Unsubscribe')], default='registration', max_length=5)),
                ('affected_user', models.CharField(blank=True, max_length=200)),
                ('execution_date', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('executed but not finished', 'Executed but not Finished'), ('waiting for executor approval', 'Waiting for eEecutor Approval'), ('approved by executor', 'Approved by Executor')], default='', max_length=30)),
                ('sent_email_to_exec', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('confirmed_by_exec', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('exec_confirmed_date', models.DateTimeField(blank=True)),
                ('first_source', models.CharField(choices=[('baja talento', 'Baja de Talento'), ('sharepoint', 'Sharepoint')], default='sharepoint', max_length=50)),
                ('first_source_date', models.DateTimeField(auto_now_add=True)),
                ('second_source', models.CharField(blank=True, choices=[('baja talento', 'Baja de Talento'), ('sharepoint', 'Sharepoint')], default='', max_length=50)),
                ('second_source_date', models.DateTimeField(blank=True)),
                ('registry_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='application.Application')),
                ('executor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor', to=settings.AUTH_USER_MODEL)),
                ('first_source_executor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_source_exec', to=settings.AUTH_USER_MODEL)),
                ('second_source_executor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_source_exec', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
