# Generated by Django 2.1.7 on 2019-09-05 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoxHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_date', models.DateTimeField(auto_now=True)),
                ('update', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOXRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(blank=True, max_length=25, null=True)),
                ('request_type', models.CharField(choices=[('registration', 'Registration'), ('unsubscribe', 'Unsubscribe')], default='registration', max_length=30)),
                ('affected_user', models.CharField(blank=True, max_length=200)),
                ('execution_date', models.DateField(blank=True, default='2019-03-20')),
                ('status', models.CharField(choices=[('executed but not finished', 'Executed but not Finished'), ('waiting for executor approval', 'Waiting for Executor Approval'), ('approved by executor', 'Approved by Executor')], default='', max_length=30)),
                ('sent_email_to_exec', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('confirmed_by_exec', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('exec_confirmed_date', models.DateField(blank=True, null=True)),
                ('first_source', models.CharField(choices=[('baja talento', 'Baja de Talento'), ('sharepoint', 'Sharepoint'), ('service now', 'Service Now')], default='sharepoint', max_length=50)),
                ('first_source_date', models.DateField(blank=True, null=True)),
                ('second_source', models.CharField(blank=True, choices=[('baja talento', 'Baja de Talento'), ('sharepoint', 'Sharepoint'), ('service now', 'Service Now')], default='', max_length=50)),
                ('second_source_date', models.DateField(blank=True, null=True)),
                ('registry_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='application.Application')),
                ('executor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor', to=settings.AUTH_USER_MODEL)),
                ('first_source_executor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_source_exec', to=settings.AUTH_USER_MODEL)),
                ('second_source_executor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_source_exec', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_sox_list', 'Can visualize sox apps list'), ('create_sox', 'Can create new SOX'), ('update_sox', 'Can update a SOX reg'), ('disable_sox', 'Can disable SOX')),
            },
        ),
        migrations.AddField(
            model_name='soxhistory',
            name='sox',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='sox.SOXRegistry'),
        ),
        migrations.AddField(
            model_name='soxhistory',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
