# Generated by Django 2.1.7 on 2019-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxregistry',
            name='status',
            field=models.CharField(choices=[('executed but not finished', 'Executed but not Finished'), ('waiting for executor approval', 'Waiting for Executor Approval'), ('approved by executor', 'Approved by Executor')], default='', max_length=30),
        ),
    ]
