# Generated by Django 2.1.7 on 2019-03-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0003_soxregistry_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxregistry',
            name='exec_confirmed_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='soxregistry',
            name='execution_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='soxregistry',
            name='first_source_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soxregistry',
            name='second_source_date',
            field=models.DateField(blank=True),
        ),
    ]
