# Generated by Django 2.1.7 on 2019-03-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0004_auto_20190314_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxregistry',
            name='first_source_date',
            field=models.DateField(blank=True),
        ),
    ]
