# Generated by Django 2.1.7 on 2019-03-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0006_auto_20190314_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxregistry',
            name='folio_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='soxregistry',
            name='request_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('unsubscribe', 'Unsubscribe')], default='registration', max_length=30),
        ),
    ]
