# Generated by Django 2.1.7 on 2019-03-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0008_auto_20190314_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxregistry',
            name='second_source_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
