# Generated by Django 2.1.7 on 2019-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0012_auto_20190316_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxregistry',
            name='first_source_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
