# Generated by Django 2.1.7 on 2019-03-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0013_auto_20190320_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxregistry',
            name='execution_date',
            field=models.DateField(blank=True, default='2019-03-20'),
        ),
    ]
