# Generated by Django 2.1.7 on 2019-03-24 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sox', '0014_auto_20190322_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoxtHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_date', models.DateTimeField(auto_now=True)),
                ('update', models.BooleanField(default=True)),
                ('sox', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='sox.SOXRegistry')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
