# Generated by Django 2.1.7 on 2019-05-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0016_auto_20190324_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soxregistry',
            options={'permissions': (('can_disable_sox', 'Can disable SOX'),)},
        ),
        migrations.AlterField(
            model_name='soxregistry',
            name='first_source',
            field=models.CharField(choices=[('baja talento', 'Baja de Talento'), ('sharepoint', 'Sharepoint'), ('service now', 'Service Now')], default='sharepoint', max_length=50),
        ),
        migrations.AlterField(
            model_name='soxregistry',
            name='second_source',
            field=models.CharField(blank=True, choices=[('baja talento', 'Baja de Talento'), ('sharepoint', 'Sharepoint'), ('service now', 'Service Now')], default='', max_length=50),
        ),
    ]
