# Generated by Django 2.1.7 on 2019-05-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sox', '0017_auto_20190501_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soxregistry',
            options={'permissions': (('view_sox_list', 'Can visualize sox apps list'), ('create_sox', 'Can create new SOX'), ('update_sox', 'Can update a SOX reg'), ('disable_sox', 'Can disable SOX'))},
        ),
    ]
