# Generated by Django 2.1.7 on 2020-04-27 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('article_version', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/wiki_module/articles/')),
                ('views', models.CharField(blank=True, max_length=10)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='art_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_app_article_list', 'Visualize App Article List'), ('create_app_article', 'Create App Article'), ('versioning_app_article', 'Versioning App Article'), ('deactivate_app_article', 'Deactivate App Article')),
            },
        ),
        migrations.CreateModel(
            name='BlogDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(max_length=15000)),
                ('blog_tags', models.TextField(blank=True, max_length=250, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=8)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_app_document_list', 'Visualize AppDocs List'), ('create_app_document', 'Create new AppDoc'), ('update_app_document', 'Update current AppDoc')),
            },
        ),
        migrations.CreateModel(
            name='WikiModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_visits', models.CharField(blank=True, max_length=999999, null=True)),
            ],
            options={
                'permissions': (('view_wiki_module', 'Visualize Wiki Module'),),
            },
        ),
    ]
