# Generated by Django 2.1.7 on 2020-04-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='art_version',
            new_name='article_version',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(max_length=8),
        ),
    ]
