# Generated by Django 2.1.7 on 2020-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0002_auto_20200428_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdoc',
            name='views',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='blogdoc',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
    ]
