# Generated by Django 2.1.7 on 2020-04-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0002_auto_20200407_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='desc',
        ),
    ]
