# Generated by Django 2.1.7 on 2020-04-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0003_auto_20200428_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdoc',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
