# Generated by Django 2.1.7 on 2020-04-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0003_auto_20200407_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('view_app_article_list', 'Visualize App Article List'), ('create_app_article', 'Create App Article'), ('versioning_app_article', 'Versioning App Article'), ('deactivate_app_article', 'Deactivate App Article'))},
        ),
    ]
