# Generated by Django 2.1.7 on 2020-04-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0004_auto_20200428_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='views',
            field=models.IntegerField(),
        ),
    ]
