# Generated by Django 2.1.7 on 2020-04-19 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki_module', '0005_appdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdocument',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appdocument',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='art_update_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
