# Generated by Django 2.1.7 on 2020-05-06 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki_module', '0005_auto_20200428_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=10)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='wikimodule',
            name='article_visits',
        ),
        migrations.AddField(
            model_name='articlefile',
            name='key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='blogdoc',
            name='key',
            field=models.CharField(default='', max_length=10),
        ),
    ]
