# Generated by Django 2.1.7 on 2020-04-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0006_auto_20200418_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdocument',
            options={'permissions': (('view_app_document_list', 'Visualize AppDocs List'), ('create_app_document', 'Create new AppDoc'), ('update_app_document', 'Update current AppDoc'))},
        ),
    ]
