# Generated by Django 2.1.7 on 2020-05-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0006_auto_20200506_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='key',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogdoc',
            name='key',
            field=models.CharField(default='', max_length=500),
        ),
    ]
