# Generated by Django 2.1.7 on 2020-04-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0007_auto_20200418_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/wiki_module/articles/'),
        ),
    ]
