# Generated by Django 2.1.7 on 2020-06-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_module', '0009_blogdoc_related_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdoc',
            name='blog_tags',
        ),
    ]
