# Generated by Django 2.1.7 on 2020-04-23 02:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki_module', '0010_auto_20200422_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticleFile',
        ),
        migrations.RenameModel(
            old_name='AppDocument',
            new_name='BlogDoc',
        ),
    ]
