# Generated by Django 2.1.7 on 2020-02-10 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baja',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
