# Generated by Django 2.1.7 on 2020-02-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20191116_1254'),
        ('bajas_semanales', '0003_auto_20200209_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajassemanales',
            name='application',
        ),
        migrations.AddField(
            model_name='bajassemanales',
            name='application',
            field=models.ManyToManyField(to='application.Application'),
        ),
    ]
