# Generated by Django 2.1.7 on 2020-02-10 03:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_application_is_for_bajas_semanales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bajas_semanales', '0004_auto_20200209_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BajasSemanales',
            new_name='BajaSemanal',
        ),
    ]
