# Generated by Django 2.1.7 on 2020-02-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0005_auto_20200209_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bajasemanal',
            options={'permissions': (('view_bajas_semanales_list', 'Visualize Bajas Semanales list'), ('create_baja_semanal', 'Create Baja Semanale'), ('update_baja_semanal', 'Update Bajas Semanales'))},
        ),
    ]
