# Generated by Django 2.1.7 on 2020-02-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0006_auto_20200209_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajasemanal',
            old_name='tipo',
            new_name='type',
        ),
    ]
