# Generated by Django 2.1.7 on 2020-02-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0007_auto_20200210_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajasemanal',
            name='already_checked',
            field=models.BooleanField(default=False),
        ),
    ]
