# Generated by Django 2.1.7 on 2020-02-13 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0009_tipobaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajasemanal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bajas_semanales.TipoBaja'),
        ),
    ]
