# Generated by Django 2.1.7 on 2020-02-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0011_auto_20200213_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobaja',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
