# Generated by Django 2.1.7 on 2020-02-28 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bajas_semanales', '0015_auto_20200214_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajasemanal',
            name='last_updated_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_updated_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
