# Generated by Django 2.1.7 on 2020-02-28 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0016_bajasemanal_last_updated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajasemanal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
