# Generated by Django 2.1.7 on 2020-02-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0017_auto_20200228_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajasemanal',
            old_name='last_updated_user',
            new_name='last_user_update',
        ),
    ]
