# Generated by Django 2.1.7 on 2020-06-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_semanales', '0018_auto_20200228_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajasemanal',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
