# Generated by Django 2.1.7 on 2019-09-05 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasPorCobrarHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_code', models.CharField(default='', max_length=6)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('processed_by_year', models.BooleanField(default=False)),
                ('processed_by_month', models.BooleanField(default=False)),
                ('processed_years', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_months', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuentas por cobrar Historie',
                'permissions': (('view_cuentas_por_cobrar', 'Can visualize cuentas por cobrar dashboard'), ('process_cuentas_por_cobrar', 'Can process cuentas por cobrar')),
            },
        ),
    ]
