# Generated by Django 2.1.7 on 2020-07-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_period', models.CharField(max_length=25, null=True)),
                ('proper_account_period', models.CharField(max_length=25, null=True)),
                ('company_code', models.CharField(max_length=25, null=True)),
                ('journa_entry', models.CharField(max_length=25, null=True)),
                ('debit_account_number', models.CharField(max_length=25, null=True)),
                ('debit_center_number', models.CharField(max_length=25, null=True)),
                ('credit_account_number', models.CharField(max_length=25, null=True)),
                ('credit_center_number', models.CharField(max_length=25, null=True)),
                ('account_event', models.CharField(max_length=25, null=True)),
                ('account_type', models.CharField(max_length=25, null=True)),
                ('mapping_number', models.CharField(max_length=25, null=True)),
                ('local_amount', models.CharField(max_length=25, null=True)),
                ('local_currency', models.CharField(max_length=25, null=True)),
                ('host_amount', models.CharField(max_length=25, null=True)),
                ('host_currency', models.CharField(max_length=25, null=True)),
                ('reference_code', models.CharField(max_length=25, null=True)),
                ('transaction_key', models.CharField(max_length=25, null=True)),
                ('reference_date', models.CharField(max_length=25, null=True)),
                ('revenue_and_nonrevenue', models.CharField(max_length=25, null=True)),
                ('suspense_type', models.CharField(max_length=25, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cuentasporcobrarhistory',
            options={'permissions': (('view_cuentas_por_cobrar', 'Can visualize cuentas por cobrar dashboard'), ('process_cuentas_por_cobrar', 'Can process cuentas por cobrar')), 'verbose_name': 'Cuentas por cobrar History'},
        ),
    ]
