# Generated by Django 2.1.7 on 2020-07-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_modules', '0002_auto_20200722_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='journa_entry',
            new_name='journal_entry',
        ),
    ]
