# Generated by Django 2.1.7 on 2019-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_modules', '0002_auto_20190726_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentasporcobrarhistory',
            options={'verbose_name': 'Cuentas por cobrar Historie'},
        ),
        migrations.AddField(
            model_name='cuentasporcobrarhistory',
            name='processed_months',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
