# Generated by Django 2.1.7 on 2019-07-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_modules', '0004_cuentasporcobrarhistory_process_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentasporcobrarhistory',
            options={'permissions': (('view_cuentas_por_cobrar', 'Can visualize cuentas por cobrar dashboard'), ('process_cuentas_por_cobrar', 'Can process cuentas por cobrar')), 'verbose_name': 'Cuentas por cobrar Historie'},
        ),
    ]
