# Generated by Django 2.1.7 on 2019-09-05 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registry_date', models.DateTimeField(auto_now_add=True)),
                ('app_type', models.CharField(choices=[('NORMAL', 'Normal'), ('SOX', 'Sox')], default='Normal', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_application_list', 'Can visualize the applications list'), ('create_application', 'Can create application'), ('update_application', 'Can update application'), ('disable_application', 'Can disable Application')),
            },
        ),
    ]
