# Generated by Django 2.1.7 on 2019-03-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('SOX', 'sox')], default='normal', max_length=6),
        ),
        migrations.AddField(
            model_name='application',
            name='folio_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
