# Generated by Django 2.1.7 on 2019-11-06 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TresSesentaEnUnClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(blank=True, max_length=250)),
                ('ambassador_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default=(('INTERNAL', 'Internal'), ('EXTERNAL', 'External')), max_length=20)),
                ('ambassador_id', models.CharField(max_length=6)),
                ('ambassador_email', models.CharField(max_length=50)),
                ('registry_date', models.DateTimeField(auto_now_add=True)),
                ('first_boss_id', models.CharField(blank=True, max_length=6, null=True)),
                ('first_boss_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
