# Generated by Django 2.1.7 on 2019-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190301_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SOX', 'Sox')], default='Normal', max_length=6),
        ),
    ]
