# Generated by Django 2.1.7 on 2019-11-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tressesentaenunclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='tressesentaenunclick',
            name='excecution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
