# Generated by Django 2.1.7 on 2019-11-06 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_tressesentaenunclick_excecution_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zendesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Registry', 'registry'), ('Unsubscribe', 'unsubscribe'), ('Update', 'update')], default='Registry', max_length=20)),
                ('previous_agent_name', models.CharField(max_length=100)),
                ('previous_agent_email', models.CharField(max_length=50)),
                ('current_agent_name', models.CharField(max_length=100)),
                ('current_agent_email', models.CharField(max_length=50)),
                ('group', models.CharField(blank=True, max_length=500, null=True)),
                ('registry_date', models.DateTimeField(auto_now_add=True)),
                ('excecution_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tressesentaenunclick',
            name='type',
            field=models.CharField(choices=[('Registry', 'registry'), ('Unsubscribe', 'unsubscribe'), ('Update', 'update')], default='Registry', max_length=20),
        ),
    ]
