# Generated by Django 2.1.7 on 2019-03-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190301_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='folio_no',
        ),
        migrations.RemoveField(
            model_name='application',
            name='movement_type',
        ),
    ]
