# Generated by Django 2.1.7 on 2019-11-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20191105_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetTracer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(blank=True, max_length=6, null=True)),
                ('ambassador_full_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(blank=True, max_length=6, null=True)),
                ('ambassador_full_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartKargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(blank=True, max_length=6, null=True)),
                ('rol', models.CharField(choices=[('GSA (Operations)', 'GSA'), ('GHA', 'GHA')], default='GSA (Operations)', max_length=25)),
                ('station', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tressesentaenunclick',
            name='excecution_date',
        ),
        migrations.RemoveField(
            model_name='tressesentaenunclick',
            name='registry_date',
        ),
        migrations.RemoveField(
            model_name='tressesentaenunclick',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='tressesentaenunclick',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tressesentaenunclick',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tressesentaenunclick',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zendesk',
            name='excecution_date',
        ),
        migrations.RemoveField(
            model_name='zendesk',
            name='group',
        ),
        migrations.RemoveField(
            model_name='zendesk',
            name='registry_date',
        ),
        migrations.RemoveField(
            model_name='zendesk',
            name='title',
        ),
        migrations.RemoveField(
            model_name='zendesk',
            name='type',
        ),
        migrations.RemoveField(
            model_name='zendesk',
            name='user',
        ),
        migrations.AlterField(
            model_name='tressesentaenunclick',
            name='ambassador_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='Aeropuertos', max_length=20),
        ),
    ]
