# Generated by Django 2.1.7 on 2019-05-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190301_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_disable_application', 'Can disable Application'),)},
        ),
    ]
