# Generated by Django 2.1.7 on 2019-05-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190501_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('view_application_list', 'Can visualize the applications list'), ('create_application', 'Can create application'), ('update_application', 'Can update application'), ('disable_application', 'Can disable Application'))},
        ),
    ]
