# Generated by Django 2.1.7 on 2019-11-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20191115_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskgroup',
            name='group',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
