# Generated by Django 2.1.7 on 2019-09-05 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_number', models.CharField(max_length=12, null=True)),
                ('type', models.CharField(choices=[('Registry', 'registry'), ('Unsubscribe', 'unsubscribe'), ('Update', 'update')], default='Registry', max_length=20)),
                ('exec_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('summary', models.CharField(max_length=500)),
                ('extra_comments', models.CharField(max_length=500)),
                ('inc_source', models.CharField(max_length=25)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
