# Generated by Django 2.1.7 on 2019-09-08 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0005_auto_20190908_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 17, 39, 29, 425910)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='exec_date',
            field=models.DateField(),
        ),
    ]
