# Generated by Django 2.1.7 on 2019-09-08 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0008_auto_20190908_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 23, 43, 46, 12947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='extra_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
