# Generated by Django 2.1.7 on 2019-09-11 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0009_auto_20190908_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 22, 16, 6, 342276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='inc_source',
            field=models.CharField(choices=[('Paperless', 'paperless'), ('Bajas Talento', 'bajas talento'), ('Other', 'other')], default='Paperless', max_length=25),
        ),
    ]
