# Generated by Django 2.1.7 on 2019-09-12 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0013_auto_20190911_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 5, 22, 52, 580509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='inc_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
