# Generated by Django 2.1.7 on 2019-09-21 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0014_auto_20190912_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 15, 44, 29, 858860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='extra_comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
