# Generated by Django 2.1.7 on 2019-09-21 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0015_auto_20190921_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 22, 53, 37, 867083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
