# Generated by Django 2.1.7 on 2019-09-22 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0017_auto_20190922_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 16, 55, 48, 57029)),
        ),
    ]
