# Generated by Django 2.1.7 on 2019-09-22 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0018_auto_20190922_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 16, 59, 1, 924269)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
