# Generated by Django 2.1.7 on 2019-09-28 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0022_auto_20190927_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraincident',
            name='close_comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 22, 53, 8, 592435)),
        ),
    ]
