# Generated by Django 2.1.7 on 2019-09-28 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0023_auto_20190927_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraincident',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 23, 2, 29, 823190)),
        ),
    ]
