# Generated by Django 2.1.7 on 2019-10-01 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0025_auto_20190928_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 22, 25, 56, 94787)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 22, 25, 56, 94665)),
        ),
    ]
