# Generated by Django 2.1.7 on 2019-10-01 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0027_auto_20190930_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraincident',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 22, 51, 10, 950062)),
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='end_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
