# Generated by Django 2.1.7 on 2019-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0030_auto_20190930_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraincident',
            old_name='inc_number',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='extraincident',
            name='close_comment',
        ),
        migrations.RemoveField(
            model_name='extraincident',
            name='closed',
        ),
        migrations.AlterField(
            model_name='extraincident',
            name='exec_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
