# Generated by Django 2.1.7 on 2019-11-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20191107_2341'),
        ('extra_incidents', '0032_extraincident_zendesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraincident',
            name='nettracer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.NetTracer'),
        ),
        migrations.AddField(
            model_name='extraincident',
            name='opcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.OpCenter'),
        ),
        migrations.AddField(
            model_name='extraincident',
            name='smartkargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.SmartKargo'),
        ),
    ]
