# Generated by Django 2.1.7 on 2019-11-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0033_auto_20191108_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraincident',
            name='exec_date',
        ),
    ]
