# Generated by Django 2.1.7 on 2019-12-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_incidents', '0035_auto_20191108_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraincident',
            options={'permissions': (('view_extra_incident_list', 'Visualize Extra Incident List'), ('create_extra_incident', 'Create extra incident'), ('disable_extra_incident', 'Disable extra incident'), ('view_extra_incident_detail', 'Visualize Extra Incident Detail'), ('finalize_extra_incident', 'Finalize Extra Incident'))},
        ),
    ]
